name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Setup spack
      uses: spack/setup-spack@v2
      with:
        ref: develop
        color: true
        path: spack
        buildcache: false

    - name: Find external packages
      run: |
        spack -e tests external find --not-buildable cmake
        spack -e tests external find --not-buildable perl
        spack -e tests external find --not-buildable gmake

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e tests concretize -f
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_BEDROCK=ON \
                 -DCMAKE_BUILD_TYPE=RelWithDebInfo
        make
        ctest --output-on-failure
